### ISSUE TITLE
Test Plan - test scenario purpose

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#10]
Each test scenario (group) needs to describe it purpose and intent. This is at the group level. Currently it is empty. TCAMT needs to support entry. IZ tool needs to display.

**Comment by Jungyubw** [comment]
fixed and shown at next reployment

**Comment by smartinez290** [comment]
@haffo Done. It needs to be implemented in the IZtool.

**Comment by haffo** [comment]
Fixed.
