### ISSUE TITLE
Understanding Immunization Meaningful Use Certification Testing

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#104]
Per Sheryl, waiting for your review.

**Comment by robnist** [comment]
Reviewed. Provided comments to Sheryl. It is ready to be posted.

**Comment by robnist** [comment]
Actually you need to close after it has been posted in tool.

**Comment by smartinez290** [comment]
Sheryl sent an updated version. Please update using the attached file.[UnderstandingImmunizationMsg_ONCCertificationTesting 2015 Edition V1.0 for PubCom.pptx](https://files.zenhub.io/56423988d83c0705616ef199)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
