### ISSUE TITLE
Message Validation Report

### ISSUE THREAD

**Issue by Jungyubw** [haffo/hit-iz-tool#105]
Hossam,

We need to modify Profile Information in the Validation Report.

Please see this word file.

Thnaks.
[Message Validation ReportCFCB.docx](https://github.com/haffo/hit-iz-tool/files/22038/Message.Validation.ReportCFCB.docx)

**Comment by Jungyubw** [comment]
Here is updated mapping document.


[Message.Validation.ReportCFCB-20151030.docx](https://github.com/haffo/hit-iz-tool/files/24576/Message.Validation.ReportCFCB-20151030.docx)

**Comment by HossamT** [comment]
@haffo This has been added to the Unified Report Library please use version 0.0.6

**Comment by robnist** [comment]
Looks good to me

**Comment by smartinez290** [comment]
The "Name" field has the "Identifier" value. The profile "Name" and  the specification values are missing form both context-free and context-base report.

**Comment by HossamT** [comment]
@Jungyubw Profiles have to be updated

**Comment by Jungyubw** [comment]
Fixed
