### ISSUE TITLE
Add MSH 22 and 23 to TDS

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#106]
Add data to test data specification when data is in the message. Usually we don't need it for MSH but here we do.

![image](https://cloud.githubusercontent.com/assets/14874904/10775530/9114f13e-7cdf-11e5-8329-5f6d3804c339.png)

**Comment by smartinez290** [comment]
@robnist Should I add also to the Z22 TDS? and which title should I used? Sending/Receiving Organizations?

**Comment by robnist** [comment]
Hold off, I think I going to add in the test story. Still deciding. Update ticket to indicate the option of adding it there.

**Comment by smartinez290** [comment]
Per Rob: Hold off, I think I going to add in the test story. Still deciding. Update ticket to indicate the option of adding it there.

**Comment by smartinez290** [comment]
Updated ticket to indicate the option of adding MSH-22 and 23 to the Test Story.

**Comment by robnist** [comment]
Added in test story when I'd is used. For MSH-23.1 and MSH-22.1 system should be set up to configure.
