### ISSUE TITLE
Profile viewer expanded view spacing is not good

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#110]
Spacing not good....

![image](https://cloud.githubusercontent.com/assets/14874904/10795971/7b88c898-7d72-11e5-92b2-519d7657f5bb.png)

**Comment by smartinez290** [comment]
Rob, there  is nothing that Harold can do about this one.

**Comment by robnist** [comment]
I disagree and do not close the ticket. Maybe the widget that is provided at this time by Angular is poor and it will be fixed in the future. Or others out in the community will find a solution. I can’t believe any commercial application would accept this, nor should we. Please keep as a long term task while a solution is found.

Technically, I don’t understand it. 20 years we would calculate available screen, column longest length, and adjust accordingly. I’m mystified. Whoever wrote the angular widget did not do a good job….

-r

**Comment by haffo** [comment]
What is the issue again ?

**Comment by haffo** [comment]
20 years ago we didn't have multiple screen sizes (tablet,phone, large screen size, medium screen size etc...) It is more complex than calculating the size and adjust. The  profile-viewer is screen size adaptive. So it is determining the size a column depending on the others column and the screen resolution.

By the way google (creator of angularjs) will be mystified by your comments as well :-)

**Comment by robnist** [comment]
Let me take a look at the code.  :<)

I’m sure Google would not be happy if we sent them our example. Regardless of all the screen sizes, how can they make one column 60 characters long when data is (will be) never longer that 25? Is there configuration settings “never make more than 25 characters, i.e., max_column_len”, I’m still mystified!

**Comment by haffo** [comment]
The column size is not dependent of the data size. We have to fix the column size.
 If we have to determine the column size by the data size, we have to go through the whole  tree to determine the longest data per column and then set the size of the column. This can take a long time. 

I am not sure it is worth loosing performance for that.

**Comment by robnist** [comment]
But we don’t have to do that. We know beforehand that the message element names is  max 25, usage = 1 or 2, etc.
Why we would parse the tree to determine something we alreay know?

**Comment by haffo** [comment]
OK. So we still want to fix the column width but with a maximum length of 25. Will do. 
Harold
