### ISSUE TITLE
Message Content Group-Segment Display issue

### ISSUE THREAD

**Issue by Jungyubw** [haffo/hit-iz-tool#113]
Srini,

As we discussed, I modified XML of message contents to add **InstancePath** attribute on the segment.
Please start to work to display Group informaiton for segment.

```
<Segment Description="Observation/Result" InstancePath="ORDER[1].OBSERVATION[2].OBX[1]" Name="OBX">
```

If you have any question/issue, let me know.

Here is full example input XML:

[ExampleOfMessageContentXML.txt](https://github.com/haffo/hit-iz-tool/files/23674/ExampleOfMessageContentXML.txt)

**Comment by smartinez290** [comment]
@sriniadhiwork what is the status on this ticket?

**Comment by sriniadhiwork** [comment]
Somehow missed this ticket from Woo. Working on it.

Thanks,
Srini

**Comment by smartinez290** [comment]
@sriniadhiwork can I close this issue?

**Comment by sriniadhiwork** [comment]
no Sandra.. yesterday discussed with Rob regarding a particular implementation.. he liked it. I am working on it.

**Comment by smartinez290** [comment]
@sriniadhiwork let me know when you are done with this issue and please help me QA it, because I am not sure what I should be looking for. Thanks.

**Comment by sriniadhiwork** [comment]
Hi @robnist 

We discussed this a while ago and Woo provided me with segment information from tcamt... 

Please let me know if this implementation is useful - the Messagecontent FULL tab will change to display the accordion showing the segment grouping + instance info - 

[Click here for full preview; screenshot below](http://embed.plnkr.co/eEMvw6TuoOF48xClE44N/)

![image](https://cloud.githubusercontent.com/assets/8129541/12930385/f0105382-cf45-11e5-9116-162b7d7b6066.png)
