### ISSUE TITLE
Z42 OBX set id 

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#114]
Could you take a look at this issue. I remember testing this before and it was working. the Set ID can restart within a message or continue with the next number in sequence within the message, per the following correction.
 
 Per Hossam,
The bug doesn't come from the validator, it's in the RSP-Z42 Constraints File.

In the Constraints File, both SetID and IZSetID are used :

SetID :
<ByName Name="RSP_K11.IZ_HISTORY_FORECAST.OBSERVATION">
                <Constraint ID="IZ-20" Target="1[1].1[1]">
                    <Description>The Value of OBX-1 (Set ID-OBX) SHALL be valued sequentially starting with the value "1" within a message.</Description>
                    <Assertion>
                        <SetID Path="1[1].1[1]"/>
                    </Assertion>
                </Constraint>
</ByName>
IZSetID :

            <ByID ID="e13dfbab-8832-4c3f-bfa5-0e9c18e644c4">
                <Constraint ID="IZ-20" Target="8[1].4[1].1[1]">
                    <Description>The Value of OBX-1 (Set ID-OBX) SHALL be valued sequentially starting with the value "1" within a message.</Description>
                    <Assertion>
                        <IZSetID Parent="8[*]" Element="4[*].1[*].1[*]" />
                    </Assertion>
                </Constraint>
            </ByID>

The IZSetID doesn't trigger an error. However, the SetID constraint triggers an error when the Set ID of OBX is not reinitialized for each group. You need to modify the Constraints File and remove the SetID constraint.

**Comment by Jungyubw** [comment]
Fixed and updated.

It will be shown at next deployment.
