### ISSUE TITLE
Test Story Font size

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#115]
Font size should be controlled by the user. However, in TCAMT, I'm trying to change everything to size 3 but this is not always possible for some text boxes and I have no clue why. T

**Comment by Jungyubw** [comment]
Let's have a meeting for this with Anusha, Sandra, and Woo.

**Comment by smartinez290** [comment]
@Jungyubw do you still need a meeting for this issue?

**Comment by smartinez290** [comment]
@Jungyubw Do you still need a meeting for this ticket?

**Comment by Jungyubw** [comment]
Nope
