### ISSUE TITLE
No indication when no validation is performed

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#117]
We need to have sanity checks and issue a proper message. 
Here they are extra <CR> and the validation chokes, but should return something about why it choked.

I assigned to Hossam fist might might be Harold.

MSH|^~\&|MyIIS|StatePH|MYEHR|DCS|20141031145233-0500||RSP^K11^RSP_K11|443533469|P|2.5.1|||NE|NE|||||Z42^CDCPHINVS|DCS^^^^^DCS^XX^^^6439432|StatePH

MSA|AA|793543||||

QAK|37374859|OK|Z44^request evaluated Immunization history^CDCPHINVS|||

QPD|Z44^Request Evaluated History and Forecast^CDCPHINVS |37374859|123456^^^MYEHR^MR|Stanley^Clement^S^^^^L|Smith^^^^^^M|19950101|M|10 East Main St^^Titletown^WI^^^L|^PRN^PH^^1^690^1231234

PID|1||123456^^^MYEHR^MR~34500907^^^MyIIS^SR||Stanley^Clement^S^^^^L||19950101|M|||10 East Main St^^Titletown^WI^^^L

ORC|RE||193337027^DCS|||||||^Clerk^Myron||^Pediatric^MARY^^^^^^^L^^^^^^^^^^^MD|||||||||||||||||||

RXA|0|1|20151029|20151029|140^seasonal flu^CVX|0.5|mL^^UCUM||00^new immunization record^NIP001|^Sticker^Nurse|^^^DCS_DC||||33k2a||PMC^sanofi^MVX|||CP|A|||||

RXR|C28161^IM^NCIT|||||

OBX|1|CE|30956-7^vaccine type^LN|13|88^influenza NOS^CVX ||||||F||||||||||||||

OBX|2|CE|59779-9^Immunization Schedule used^LN|13|VXC16^ACIP^CDCPHINVS||||||F|||20151029|||||||||||

OBX|3|ID|59781-5^dose validity^LN|13|Y||||||F|||20151029

ORC|RE||9999^DCS|||||||^Clerk^Myron|||||||DCS^Dabig Clinical System^HL70362||||||||||||||

RXA|0|1|20151029|20151029|998^no vaccine admin^CVX|999||||||||||||||NA||||||

OBX|4|CE|30956-7^vaccine type^LN|14|152^pcv NOS^CVX ||||||F||||||||||||||

OBX|5|CE|59779-9^Immunization Schedule used^LN|14|VXC16^ACIP^CDCPHINVS||||||F||||||||||||||

OBX|6|DT|30980-7^Date vaccination due^LN|14|20600101||||||F||||||||||||||

OBX|7|DT|30981-5^Earliest Date to give^LN|14|20600101||||||F||||||||||||||

OBX|8|CE|30956-7^vaccine type^LN|15|88^influenza NOS^CVX ||||||F||||||||||||||

OBX|9|CE|59779-9^Immunization Schedule used^LN|15|VXC16^ACIP^CDCPHINVS||||||F||||||||||||||

OBX|10|DT|30980-7^Date vaccination due^LN|15|20160901||||||F||||||||||||||

OBX|11|DT|30981-5^Earliest Date to give^LN|15|20160901||||||F||||||||||||||

OBX|12|CE|30956-7^vaccine type^LN|14|03^MMR^CVX ||||||F||||||||||||||

OBX|13|CE|59779-9^Immunization Schedule used^LN|14|VXC16^ACIP^CDCPHINVS||||||F||||||||||||||

OBX|14|DT|30980-7^Date vaccination due^LN|14|19960101||||||F||||||||||||||
OBX|17|CE|59779-9^Immunization Schedule used^LN|15|VXC16^ACIP^CDCPHINVS||||||F||||||||||||||

OBX|18|DT|30980-7^Date vaccination due^LN|15|19960101||||||F||||||||||||||

OBX|19|DT|30981-5^Earliest Date to give^LN|15|19960101||||||F||||||||||||||

OBX|20|CE|30956-7^vaccine type^LN|14|45^Hep B^CVX ||||||F||||||||||||||

OBX|21|CE|59779-9^Immunization Schedule used^LN|14|VXC16^ACIP^CDCPHINVS||||||F||||||||||||||

OBX|22|DT|30980-7^Date vaccination due^LN|14|19950101||||||F||||||||||||||

OBX|23|DT|30981-5^Earliest Date to give^LN|14|19950101||||||F||||||||||||||

OBX|24|CE|30956-7^vaccine type^LN|15|108^MCV^CVX ||||||F||||||||||||||

OBX|25|CE|59779-9^Immunization Schedule used^LN|15|VXC16^ACIP^CDCPHINVS||||||F||||||||||||||

OBX|26|DT|30980-7^Date vaccination due^LN|15|20110101||||||F||||||||||||||

OBX|27|DT|30981-5^Earliest Date to give^LN|15|20110101||||||F||||||||||||||

OBX|28|CE|30956-7^vaccine type^LN|14|21^varicella^CVX ||||||F||||||||||||||

OBX|29|CE|59779-9^Immunization Schedule used^LN|14|VXC16^ACIP^CDCPHINVS||||||F||||||||||||||

OBX|30|DT|30980-7^Date vaccination due^LN|14|19960101||||||F||||||||||||||

OBX|31|DT|30981-5^Earliest Date to give^LN|14|19960101||||||F||||||||||||||

OBX|32|CE|30956-7^vaccine type^LN|15|115^TDAP^CVX ||||||F||||||||||||||

OBX|33|CE|59779-9^Immunization Schedule used^LN|15|VXC16^ACIP^CDCPHINVS||||||F||||||||||||||

OBX|34|DT|30980-7^Date vaccination due^LN|15|20020101||||||F||||||||||||||

OBX|35|DT|30981-5^Earliest Date to give^LN|15|20020101||||||F||||||||||||||

![image](https://cloud.githubusercontent.com/assets/14874904/10893489/fa7f01b4-8176-11e5-8bd4-df1adda63547.png)

**Comment by HossamT** [comment]
This has to be assigned to @haffo. The validation engine returns a report for this type of message (with blank lines). For each blank line the validation engine returns a detection where Category = "Invalid Content" and Classification = "Error", the error message is : " ' ' is not a valid segment definition"
