### ISSUE TITLE
 ERL_IZ data type update

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#121]
ERL-3 should be C(R/RE) CP= If ERL.4 (Field Repetition) is valued. 

This data type is used in ERR-2 in Z31,Z32, Z33 and Z42.

**Comment by Jungyubw** [comment]
fixed

**Comment by smartinez290** [comment]
Woo -- Was this fix suppose to have taken place in the latest deployment. I don't see it.


________________________________

**Comment by smartinez290** [comment]
Not fixed.

**Comment by Jungyubw** [comment]
Z23 fixed
