### ISSUE TITLE
Profile viewer to hide elements with conditional predicate is based on an optional element

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#122]
Woo, this is an issue that apparently was discussed before with Rob. The profile viewer should not show elements where the conditional predicate is based on an optional element. See RXA-5 for example. RXA-5.5 and RXA-5.6 CPs are both based on t RXA-5.4 which is optional. Harold asked me to assign this ticket to you, so you can add the "hide" attribute to the profile. Once you are done, please re-assign the ticket to Harold.

**Comment by robnist** [comment]
Yes, we discussed with Srini I thought to just look at certain data types instead of trying to figure it out algorithmically.
CE, CWE, and CNE and maybe HD.

**Comment by Jungyubw** [comment]
For this, I already added attribute "Hide" for CE and CWE.
Harold, please add a function hide for IZ tool profile viewer.

**Comment by smartinez290** [comment]
Not fixed yet.
