### ISSUE TITLE
Add Validation Result preference on the tool navigation bar 

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#123]
Add a Validation Result Preference to show Warnings, Alerts and Affirmative, in the tool navigation bar right before the "about" tab and after the "Documentation" tab. This preferences do not impact the validation report.

**Comment by smartinez290** [comment]
@haffo This has not been implemented yet.

**Comment by smartinez290** [comment]
@robnist check the tool are you ok with the location of the "Preference"? please, let me know if you are not, to ask @haffo to move it.

**Comment by robnist** [comment]
Yes.

We no longer need information and by degault do not display affirmatives.

**Comment by smartinez290** [comment]
@haffo per Rob request we no longer need information and by default do not display affirmatives.
