### ISSUE TITLE
Affirmatives in the validation report

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#124]
For the Affirmatives in the validation report, include the number of affirmative and add a note stating “details of affirmatives not included”.

**Comment by HossamT** [comment]
@haffo per our discussion I updated the Unified Report (now : 0.0.7-SNAPSHOT)
and the validation engine (now : 1.0.0-beta-11.8-SNAPSHOT)
You can use the Unified Report API to exclude any classification to be rendered from the final report like this : 

JSONObject o = new JSONObject();
o.put("excluded", "affirmative");
String HTML = report.render("iz-report", o);

**Comment by haffo** [comment]
@HossamT Is this correct ? pom can't seem to compile:
<dependency>
			<groupId>gov.nist</groupId>
			<artifactId>hl7-v2-validation</artifactId>
			<version>1.0.0-beta-11.8-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>gov.nist.healthcare.hl7.v2.unifiedreport</groupId>
			<artifactId>validation-proxy</artifactId>
			<version>0.0.7-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>gov.nist.healthcare.hl7.v2.unifiedreport</groupId>
			<artifactId>report-filter</artifactId>
			<version>0.0.7-SNAPSHOT</version>
		</dependency>

**Comment by HossamT** [comment]
@haffo My bad, you can retry now

**Comment by haffo** [comment]
@HossamT still not working. can you stop by ?
