### ISSUE TITLE
Different Sizes in Juror Document

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#130]
Needs to be what is in the Display Verification (i.e, the large size).

![image](https://cloud.githubusercontent.com/assets/14874904/10954561/31ba7310-831c-11e5-87e7-082a4a0997e7.png)

**Comment by smartinez290** [comment]
Good morning!!! Should this ticket be assigned to Anusha?

**Comment by robnist** [comment]
I think she completed this last week.

**Comment by smartinez290** [comment]
Did you look at the juror doc. they look the same to me. Please take a look and let me know if you are satisfy, so I can close the ticket.

**Comment by robnist** [comment]
I think this was fixed last week, if so close it.

**Comment by smartinez290** [comment]
@haffo, @robnist It looks like these did not make it in the last deployment.

**Comment by smartinez290** [comment]
@robnist Anusha just explained what you requested. I will close the ticket.
