### ISSUE TITLE
Validation seems to be performed twice or it is the GUI

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#133]
Probably the GUI.

This is on CHrome (might apply to others). 

I validate, I get a display of results, and then it redisplays it. Meaning the text areas goes blank and it reappears. This just starting happening about a week ago.

**Comment by haffo** [comment]
@robnist, do you have the same issue when you clear your cache ?

**Comment by robnist** [comment]
Cleared cache. Smae thing, it is now happend when a switch test cases and view the JD, TDS, etc.

**Comment by smartinez290** [comment]
@robnist and @haffo I am not sure, sure I close this issue?
