### ISSUE TITLE
MSA-2 lenght wrong in profile

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#135]
Quality control....quality control....!
Line by line inspection is required.

BTW, you should have a profile category.

![image](https://cloud.githubusercontent.com/assets/14874904/11009801/d87db248-84a7-11e5-93b9-03853a9f5710.png)

**Comment by robnist** [comment]
This applys to the ACK and RSPs.

QC!

**Comment by smartinez290** [comment]
@woo PLease update, this applies to Z23, Z31, Z32, Z33 and Z42

**Comment by Jungyubw** [comment]
Sandra. Do we need to check all of lengh values for all of profiles?  Because MSA-1 also looks wrong in the Rob's figure.

**Comment by smartinez290** [comment]
Fix these two for now. I will do a review of all the length and will report back if I find anything wrong.

**Comment by Jungyubw** [comment]
fixed
