### ISSUE TITLE
Issues with NIST-IZ-QR-1.2_Response_K11_Z42 message

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#136]
This is the message I retrieved from TCAMT, dated 10-29-2015. I think I got the one you referred and all of the others have dates that are much earlier.
There are some issues in the message, see where I highlighted. 

I did change some things that we discussed, subid, msh 3/4/5/6/22/23, and address and things but I don’t think I changed the OBXs where I high-lighted (except for sub id). Essentially this is the message in TCAMT that you referenced.

Please take a look and correct.

Thanks
Rob

 

MSH|^~\&|NIST IIS APP|NIST IIS FAC|NIST EHR APP|NIST EHR Facility|20151031145233-0500||RSP^K11^RSP_K11|NIST-IZ-QR-1.2_Response_K11_Z42|P|2.5.1|||NE|NE|||||Z42^CDCPHINVS|NIST IIS FAC^^^^^NIST-AA-1^XX^^^100-1776|NIST EHR Facility^^^^^NIST-AA-1^XX^^^100-6482
MSA|AA|NIST-IZ-QR-1.1_Query_Q11_Z44||||
QAK|IZ-1.1-2015|OK|Z44^request evaluated Immunization history^CDCPHINVS|||
QPD|Z44^Request Evaluated History and Forecast^CDCPHINVS |107374859|171122^^^NIST MPI^MR|Child^Bobbie^Q^^^^L|Que^Suzy^^^^^M|20090214|M|105 Laurel Run Rd^^Bozeman^MT^^^L|||||
PID|1||171122^^^NIST MPI^MR~34500907^^^MyIIS^SR||Child^Bobbie^Q^^^^L||20090214|M|||105 Laurel Run Rd^^Bozeman^MT^^^L||||||||||||||||||||||||||||
ORC|RE||197023^DCS|||||||^Clerk^Myron|||||||DCS^Dabig Clinical System^StateIIS||||||||||||||
RXA|0|1|20090415|20090415|31^Hep B Peds NOS^CVX|999|||01^historical record^NIP001|||||||||||CP|
OBX|1|CE|30956-7^vaccine type^LN|1|45^Hep B NOS^CVX ||||||F|||20151031|||||||||||
OBX|2|CE|59779-9^Immunization Schedule used^LN|1|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|3|ID|59781-5^dose validity^LN|1|Y||||||F|||20151031
ORC|RE||197027^DCS|||||||^Clerk^Myron||^Pediatric^MARY^^^^^^^L^^^^^^^^^^^MD|||||||||||||||||||
RXA|0|1|20090731|20090314|48^HIB PRP-T^CVX|999|||01^historic immunization record^NIP001|^Sticker^Nurse|^^^DCS_DC||||33k2a||PMC^sanofi^MVX|||CP
OBX|4|CE|30956-7^vaccine type^LN|1|17^HIB NOS^CVX ||||||F|||20151031|||||||||||
OBX|5|CE|59779-9^Immunization Schedule used^LN|1|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|6|ID|59781-5^dose validity^LN|1|N||||||F|||20151031
OBX|7|ST|30982-3^Reason applied ^LN|1|Too Young||||||F|||20151031
ORC|RE||197028^DCS|||||||^Clerk^Myron||^Pediatric^MARY^^^^^^^L^^^^^^^^^^^MD|||||||||||||||||||
RXA|0|1|20091011|20091011|110^DTAP-Hep B-IPV^CVX|999|||01^historic immunization record^NIP001||||||||SKB^GSK^MVX|||CP
OBX|7|CE|30956-7^vaccine type^LN|1|45^Hep B NOS^CVX ||||||F||||||||||||||
OBX|8|CE|59779-9^Immunization Schedule used^LN|1|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|9|ID|59781-5^dose validity^LN|1|Y||||||F|||20151031
OBX|10|CE|30956-7^vaccine type^LN|2|10^IPV^CVX ||||||F||||||||||||||
OBX|11|CE|59779-9^Immunization Schedule used^LN|2|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|12|ID|59781-5^dose validity^LN|2|Y||||||F|||20151031
OBX|13|CE|30956-7^vaccine type^LN|3|20^DTAP^CVX ||||||F||||||||||||||
OBX|14|CE|59779-9^Immunization Schedule used^LN|3|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|15|ID|59781-5^dose validity^LN|3|Y||||||F|||20151031
ORC|RE||197028^DCS|||||||^Clerk^Myron||^Pediatric^MARY^^^^^^^L^^^^^^^^^^^MD|||||||||||||||||||
RXA|0|1|20100411|20100411|08^Hep BPEDS^CVX|999|||01^historic immunization record^NIP001|^Sticker^Nurse|||||||SKB^GSK^MVX|||CP||||||
OBX|16|CE|30956-7^vaccine type^LN|1|45^Hep B NOS^CVX ||||||F|||20151031|||||||||||
OBX|17|CE|59779-9^Immunization Schedule used^LN|1|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|18|ID|59781-5^dose validity^LN|1|Y||||||F|||20151031
ORC|RE||197028^DCS|||||||^Clerk^Myron||^Pediatric^MARY^^^^^^^L^^^^^^^^^^^MD|||||||||||||||||||
RXA|0|1|20100415|20100415|03^MMR^CVX|999|||01^historic immunization record^NIP001||||||xy3939||SKB^GSK^MVX|||CP||||||
OBX|19|CE|30956-7^vaccine type^LN|1|03^MMR^CVX ||||||F|||20151031|||||||||||
OBX|20|CE|59779-9^Immunization Schedule used^LN|1|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|21|ID|59781-5^dose validity^LN|1|N||||||F|||20151031
ORC|RE||197023^DCS|||||||^Clerk^Myron|||||||DCS^Dabig Clinical System^StateIIS||||||||||||||
RXA|0|1|20091031|20091031|998^no vaccine admin^CVX|999||||||||||||||NA||||||
OBX|22|CE|30956-7^vaccine type^LN|1|03^MMR^CVX ||||||F|||20151031|||||||||||
OBX|23|CE|59779-9^Immunization Schedule used^LN|1|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|24|DT|30980-7^Date vaccination due^LN|1|20100214||||||F|||20151031|||||||||||
OBX|25|DT|30981-5^Earliest Date to give^LN|1|20100214||||||F|||20151031|||||||||||
OBX|26|CE|30956-7^vaccine type^LN|2|10^IPV^CVX ||||||F|||20151031|||||||||||
OBX|27|CE|59779-9^Immunization Schedule used^LN|2|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|28|DT|30980-7^Date vaccination due^LN|2|20100214||||||F|||20151031|||||||||||
OBX|29|DT|30980-7^Date vaccination due^LN|2|20100114||||||F|||20151031|||||||||||
OBX|28|CE|30956-7^vaccine type^LN|3|107^DTAP^CVX ||||||F|||20151031|||||||||||
OBX|29|CE|59779-9^Immunization Schedule used^LN|3|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|30|DT|30980-7^Date vaccination due^LN|3|20100214||||||F|||20151031|||||||||||
OBX|31|CE|30956-7^vaccine type^LN|4|10^IPV^CVX ||||||F|||20151031|||||||||||
OBX|32|CE|59779-9^Immunization Schedule used^LN|4|VXC16^ACIP^CDCPHINVS||||||F|||20151031|||||||||||
OBX|33|DT|30980-7^Date vaccination due^LN|4|20100214||||||F|||20151031|||||||||||

Here are the errors the tool is reporting. 
The last error is due to an issue in the profile.

**Comment by robnist** [comment]
Updated based on conversations with Rob Savage. Fixed in TCAMT. Needs final QA when in tool.

**Comment by smartinez290** [comment]
@haffo I copied and pasted this message and the tool is generating the following error: "Sorry, cannot validate the message provided. The following character(s) ['|'] has/have been used more than once as a separator."

I can't figure out what is wrong.
