### ISSUE TITLE
TCAMT- bigger message font size and view window

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#138]
Please make the font size +1 bigger and make view window twicw as big.

![image](https://cloud.githubusercontent.com/assets/14874904/11041578/b228b9ea-86e0-11e5-980e-aa9eb93e7db0.png)

**Comment by smartinez290** [comment]
@woo this ticket is in the QA, was TCAMT  re-deployed?The font is still the same.

**Comment by Jungyubw** [comment]
Not yet. I will be shown at tomorrow (11/17) redployment.
