### ISSUE TITLE
IZ-DT_D conformance statement

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#14]
What are the IZ-DT_D conformance statement IDs? -- DT_D comes from the IG, we added IZ- to identified it as a CS. Rob to review.

**Comment by robnist** [comment]
Not sure what to do with this, come by to discuss.

**Comment by smartinez290** [comment]
@robnist I am closing this one. There is a future enhancement ticket that covers this. This is related to the time stamp requirements.
