### ISSUE TITLE
Replace IZ-20 with NIST-01 -- Impacts profiles Z22,Z32 and Z42

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#144]
IZ-20 - The Value of OBX-1 (Set ID-OBX) SHALL be valued sequentially starting with the value "1" within a message.

is replace with

NIST-01 - The Value of OBX-1 (Set ID-OBX) SHALL be valued sequentially starting with the value "1" within a message or for each group.

**Comment by Jungyubw** [comment]
fixed

**Comment by smartinez290** [comment]
@Jungyubw -- the validation is generating the correct message, but I do not see the binding of NIST-01 to OBX-1 in the Profile.

**Comment by Jungyubw** [comment]
It is message level Constraint and the binding location is message root.

So it need to update IZ testing tool UI to show this binding. Please ask to Harold.

**Comment by smartinez290** [comment]
@Jungyubw Thanks! I will close this ticket and open another one for @haffo
