### ISSUE TITLE
Binding of NIST-01 to OBX-1 CS is not shown

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#146]
Per Woo, this is a message level Constraint and the binding location is message root. So it need to update IZ testing tool UI to show this binding. Please ask to Harold.
This CS applies to Z22, Z32 and Z42 profiles.

**Comment by haffo** [comment]
@Jungyubw we can talk about this when you have a chance.

**Comment by haffo** [comment]
@Jungyubw you can stop by to talk about this again.
