### ISSUE TITLE
Warning description RE revision

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#15]
Revise warning description RE. The RE (Required, but may be Empty) field …

**Comment by robnist** [comment]
Segment RXR (Pharmacy/Treatment Route) is missing. Depending on the use case and data availability it may be appropriate to value this element (Usage is "RE", Required, but may be Empty).

Basically, add "(Usage is "RE", Required, but may be Empty)." to the end of the message for RE usage.



![image](https://cloud.githubusercontent.com/assets/14874904/12784484/678e95c2-ca55-11e5-9717-e3b8cc0b4345.png)
