### ISSUE TITLE
C(O/X), C(O/O), etyc. do not display as default

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#153]
Only display C's, with a R or RE in it as the default in the profile viewer. They are display in the R,RE, C, O, X option but not the R,RE,C option.

![image](https://cloud.githubusercontent.com/assets/14874904/11190311/cd311700-8c62-11e5-9df1-93f047cb4be8.png)

**Comment by smartinez290** [comment]
@haffo Please take a look at this ticket.

**Comment by smartinez290** [comment]
@haffo not fixed yet, C(O/X) component are still showing in the R,RE,C view
