### ISSUE TITLE
Value Set Close not working

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#156]
Still takes at least 3 clicks to close.
Also, make X and CLOSE consistent. Can these all be a "Close" butten instead of X?

![image](https://cloud.githubusercontent.com/assets/14874904/11197238/2fb94510-8c8a-11e5-912b-317d67e14189.png)

**Comment by smartinez290** [comment]
@robnist, @haffo now it takes two clicks. The "x" was replaced with "XClose".
