### ISSUE TITLE
Validattion: Duplicate errors

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#16]
Filter duplicate errors (Hossam was working in this capability)

**Comment by HossamT** [comment]
@haffo Using the Unified Report artifact (report-filter module)
groupId : gov.nist.healthcare.hl7.v2.unifiedreport
artifactId : report-filter
version : 0.0.4-SNAPSHOT

Usage : 
EnhancedReport filtred = Filter.removeDuplicate(report);

**Comment by smartinez290** [comment]
@HossamT I am trying to QA this ticke, but I am not sure how. Could you show me how it was fixed? Thanks.

**Comment by HossamT** [comment]
@smartinez290 I'm not sure It was integrated with the tool, I tried locally it works but not in the tool, @haffo can you make sure that you are using this in the tool ?

**Comment by smartinez290** [comment]
Hossam, please check if this issue was solved. The tool was deployed. If it ok please close the ticket. Thanks.

**Comment by HossamT** [comment]
It's fixed.
