### ISSUE TITLE
Duplicate errors - Revert back 

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#167]
Revert back to show  all duplicate errors.

**Comment by HossamT** [comment]
I have nothing to revert back from, I created the filter that's used in the iz-tool. We only need to make it optional.

**Comment by robnist** [comment]
How is this closed without the option?

**Comment by HossamT** [comment]
Another ticket was created for Harold #169

**Comment by smartinez290** [comment]
I opened another ticket for Harold see #169
