### ISSUE TITLE
Add option to remove duplicate errors

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#169]
All errors should be display by default, a  user option should be added to remove duplicates errors from the display. 

Per Rob:

What I thought we had agreed to is this:

1.       Validation works as normal (no change)
2.       The validation report is filter to remove duplicates—but in all circumstances the validation report from the validation is the same (complete)
3.       By default the tool displays all errors
4.       The user is given an option to suppress duplicate error (i.e., the tool displays the filtered report)

Per Hossam:
Everything is implemented, the report comes back from the validation engine with all the errors.
Then in the tool the report is filtered, the only change needed is to make the duplicates filter optional.

**Comment by haffo** [comment]
@HossamT  How do you know the duplicate errors from the tool ?

**Comment by HossamT** [comment]
@haffo That's how you remove duplicates from the report : 
report = Filter.removeDuplicate(report); 

It's the only thing implemented, if you need another implementation just give me the specification
