### ISSUE TITLE
NDC/CVX validation and Test cases

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#17]
Develop test cases to support  NDC codes. Be aware of the impact to IZ-24 which will not trigger when using NDC codes.
 IZ-24: If RXA-20 is valued "CP" or "PA" and the first occurrence of RXA- 9.1 is valued “00” and RXA-5.1 is valued with a CVX code from table PHVS_VISVaccines_IIS (See Appendix A) then for each vaccine information statement that was shared there SHALL be:
• one OBX segment with OBX-3.1 valued “69764-9” (bar coded) and one OBX with OBX-3.1 valued “29769-7” (presentation /delivery date) associated. Both OBX shall have the same value in OBX-4
OR
• one OBX segment with OBX-3.1 valued “30956-7” (vaccine type) and one OBX segment with OBX-3.1 valued “29768-9” (version date) and one OBX with OBX-3.1 valued “29769-7” (presentation /delivery date) associated. All three OBX shall have the same value in OBX-4

**Comment by smartinez290** [comment]
If we support and implement multi value set binding, the IZ-24 issue still remains. This CS will not trigger if an NDC code is used.

**Comment by smartinez290** [comment]
Based on this clarification it was decided, that support for NDC is not necessary in the Context-free testing. This will avoid Craig and Rob from creating another cdc table for the NDC codes. 
 “The NIST Context-based feature in the 2015 Edition Immunization Test Suite used for ONC certification testing will verify that the Health IT Module supports NDC for new immunization records and CVX for historical immunization records in HL7 immunization messages, and the Test Cases in the Test Suite (ONC 2015 Test Plan) will reflect this requirement.”
But, then you and the developers found a solution for multi-value set binding and you thought about the possibility to support NDC/CVX also is context-free. This is where you asked me to keep the IZ-24 issue still open for you to think about it. 
Does this help to remember?
Should we remove support for NDC in the context-free testing? Or do you want to support NDC in context-free and do not worry about IZ-24? We never discussed IZ-24 and NDC with the SMEs because the decision was not to support NDC at all in context-free testing and therefore no clarification was needed. This is why I had no documentation on this.

**Comment by robnist** [comment]
What if someone validates a message in CF with an NDC code?

Thinking we could have a check button to select NDC validation. Then for this IZ-24 is not part of the profile.

**Comment by robnist** [comment]
Just document in the clarification document that IZ-24 will not trigger when NDC is used. This is dependent on the multiple value set binding.
