### ISSUE TITLE
Numbers not bullets in testing instructions

### ISSUE THREAD

**Issue by mindovina** [haffo/hit-iz-tool#171]
Under the SOAP Envelope tab.
Under the Receiver(Responder) test "SOAPENV_2_SubmitSingleMessage_Response"
If you click on the "Testing Instructions" tab.
The instructions are shown will * (bullets) instead of numbers 1-5.   Please change to numbers, thus it will match the diagram shown.

**Comment by haffo** [comment]
Done. You can check on next deployment.
