### ISSUE TITLE
TCAMT-by default remove Card and value set columns

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#175]
The Test Data and TDC columns are STILL not wide enough where other columns are too big. The most important columns are Test Data and TDC, this is the whole point of this TAB so they ALWAYS need to be completely visible. 

![image](https://cloud.githubusercontent.com/assets/14874904/11373328/b48c6ed2-929f-11e5-8f3b-1a79ab04f757.png)

**Comment by Jungyubw** [comment]
fixed and need to wait for deployment
