### ISSUE TITLE
SOAP Envelope: Incorrect text used for Description and Test Objectives

### ISSUE THREAD

**Issue by mindovina** [haffo/hit-iz-tool#176]
Under:
SOAP Envelope
Receiver(Responder)
SOAPENV_4_Security_Fault
Test Story

The text shown in Description and Test Objectives is for UnsupportedOperation_Fault, not Security_Fault.
Please use the correct text.

**Comment by smartinez290** [comment]
@mindovina please close this ticket if you think everything is correct. Thanks.

**Comment by smartinez290** [comment]
@mindovina Harold just confirmed that is fixed. I am  closing the issue.
