### ISSUE TITLE
Context-Free: Test Story

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#18]
Test story font size is way too small --  looking at the IZtool.

**Comment by Jungyubw** [comment]
fixed and shown at next redeployment

**Comment by smartinez290** [comment]
@Jungyubw Apply the Gldilocks rule.

**Comment by Jungyubw** [comment]
Fixed at next redeployemnt

**Comment by smartinez290** [comment]
Woo - Is it possible to automatically switch any font and size entered by the user to a default font and size?

**Comment by Jungyubw** [comment]
Automatically size resizing could be possible. 
Sandra, if you want it still, please create another ticket.
Thanks.

**Comment by smartinez290** [comment]
@robnist do you still want automatic re-sizing to be done?

**Comment by robnist** [comment]
No. It should be controlled by the user. However, in TCAMT, I'm trying to change everything to size 3 but this is not always possible for some text boxes and I have no clue why. This can be closed and another one opened.
