### ISSUE TITLE
Message Viewer Tree - MSH-1 and MSH-2

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#19]
See file

![error 1](https://cloud.githubusercontent.com/assets/14874904/10143124/87b0ac3a-65e4-11e5-93a5-cac91ab515fd.PNG)

**Comment by haffo** [comment]
The escaping is from the parser. @HossamT please fix this in the Parser.

**Comment by HossamT** [comment]
Fixed.
New validation engine version : 1.0.0-beta-10.9-SNAPSHOT
