### ISSUE TITLE
Update Table Section under Resources

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#191]
1. Remove T value Sets
2. Change name to Value Set (also in the download button).
3. Change Column header "File" to "File (XML Format)

![image](https://cloud.githubusercontent.com/assets/14874904/11483591/1f76812a-9777-11e5-8502-5d639cc7ec68.png)

**Comment by haffo** [comment]
Any need on generating the json for this ?

**Comment by haffo** [comment]
@robnist do we need to generate json files for this ?

**Comment by robnist** [comment]
no

**Comment by robnist** [comment]
No
