### ISSUE TITLE
Update Constraints under Resources

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#192]
1. Change name to Conformance Statements and Condition Predicates 
(I'm assuming this is really what the file contains)
2. Same for the download button
3. Remove T Profiles
4. Add JSON column if they exist in that format as well???

![image](https://cloud.githubusercontent.com/assets/14874904/11483681/c99a244a-9777-11e5-8c05-18a6097d17a5.png)

**Comment by haffo** [comment]
@Rob not all resources have their json representation. Do you want us to generate them ?

**Comment by haffo** [comment]
@robnist  there is no json file for constraints. json file are only generated for profile and vocabulary.

**Comment by robnist** [comment]
No, only if we have them and use them. For example, the profile; in one spot I saw the JSON format and another I saw the XML. This is why I said to provide both under profile resources. However, if we don’t create them for value sets, then don’t post them.

**Comment by robnist** [comment]
Only if you feel it would be useful to the end user (and it is easy to do).

**Comment by haffo** [comment]
I don't see the need of it to the user.
