### ISSUE TITLE
Profile fix needed ASAP

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#202]
For Z42:
RXA-17 usage should be C(R/O)

For Z32 and Z22
ORC-12 usage should be C(RE/O)

**Comment by Jungyubw** [comment]
Sandra.

Please make it sure this ticket. In the Z42 RXA-17 usage is currently O. Do you want to modify it C(R/O)? If so, I need Constraint Definition.

in the Z32 and Z22 ORC-12 usage is already C(RE/O).

**Comment by smartinez290** [comment]
ORC-12 : CP= If the first occurrence of RXA-9.1 is valued "00" and RXA-20 is valued "CP" or "PA"

The profile viewer is showing ORC-12 as "C" take a look.

**Comment by smartinez290** [comment]
RXA-17 CP= If the first occurrence of RXA-9.1 is valued "00" and RXA-20 is valued "CP" or "PA"

**Comment by Jungyubw** [comment]
Fixed and will be shown at next redployment of IZ tool.
