### ISSUE TITLE
Details Column

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#205]
Need to extract information from validation stack trace and provide readable information.

Need to create a table with define meta data:
1. extract info from validation trace
2. format in table
3. define meta data (Segment, occurrence, field, occurrence, assertion, source, etc.)
4. Provide option for user to have as preference to show (if possible)

Hossam, first and then Harold. Rob to help define meta data and table format.

**Comment by robnist** [comment]
Also, now that column has been removed it can be included in the details.

**Comment by HossamT** [comment]
@robnist The details apply only to detections related to content and valueSet validation, the metadata available for a ValueSet detection is : 
bindingStrength
id 
bindingLocation
extensibility
stability

And for a content validation detection (a failed constraint) : 
chapter
section
page
url
source
generatedBy
referencePath
testDataCategorization

As for the StackTrace (which is only related to content validation) : 
We have a List of failed assertions as well as the reason it failed

**Comment by smartinez290** [comment]
@robnist @HossamT wants to know if there is anything else left to do on this issue. He answered the question. Should I close it?
