### ISSUE TITLE
Add Info button to Message Content

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#207]
Add an info button or Help button will the attached content. What do you think is best?

![image](https://cloud.githubusercontent.com/assets/14874904/11547662/b077d41e-9923-11e5-947b-9b304b452186.png)
[MessageContentInfoButton.docx](https://github.com/haffo/hit-iz-tool/files/50329/MessageContentInfoButton.docx)

**Comment by haffo** [comment]
I would go with help button because the other is more complicated to do with the current  time constraint.

**Comment by haffo** [comment]
@robnist, is it how you want it ? 

![screen shot 2015-12-03 at 11 09 46 am](https://cloud.githubusercontent.com/assets/2146797/11566001/9635ecae-99ae-11e5-911a-9e0f4219faa0.png)

**Comment by robnist** [comment]
Looks good to me.
