### ISSUE TITLE
Critical: Test case update needed - RXA-17 C(R/O)

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#210]
This is the only TC that needs to be updated: IZ-QR-2.2_Response_K11_Z42

**Comment by robnist** [comment]
What needs to be updated? Data, category????

**Comment by smartinez290** [comment]
This is the error - The required Field RXA-17 (Substance Manufacturer Name) is missing. The element is required based on the condition predicate evaluation: If the value of RXA-9.1 (Identifier) is '00' AND if the value of RXA-20 (Completion Status) is one of List Values: 'CP','PA'.

A value (Substance Manufacturer Name)  is needed in RXA-17 with its data categorization

**Comment by robnist** [comment]
What needs to be done?

**Comment by smartinez290** [comment]
Problem solved. the TDC was removed, no testing will be performed for now. See future TK #217.
