### ISSUE TITLE
Test Data Spec. using codes not Text Decsp.

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#218]
In the Test Data Specification, the value for Immunization Registry Status should be Active, not just A. Similarly, the Multiple Birth Indicator should be Yes or No, not Y or N and the Completion Status should be Complete or Refused not CP or RE. We don't use message codes anywhere else in this tab.

Should check throughout for others...

![image](https://cloud.githubusercontent.com/assets/14874904/11576415/7f52083e-99e4-11e5-9ed8-e409db5ec649.png)

**Comment by smartinez290** [comment]
@sriniadhiwork I thought we have done this before, it look like I missed some. See attachment.[TDSCorrections.docx](https://files.zenhub.io/56619b51c0bdf3e365c5a4b2)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by smartinez290** [comment]
@sriniadhiwork The patient table in the Query_Z44 test cases also needs to be updated, with the expanded values given.

**Comment by sriniadhiwork** [comment]
Woo: please use please use common_tdspec.xsl [2.9.8](https://sourceforge.net/p/nistmu2hl7xslt/svn/HEAD/tree/trunk/xsl/common/common_tdspec.xsl)

PID fix: ![image](https://cloud.githubusercontent.com/assets/8129541/11598185/6188de0e-9a8e-11e5-9fc9-3eb2cdb03178.png)

QPD fix: 
![image](https://cloud.githubusercontent.com/assets/8129541/11598212/87979df6-9a8e-11e5-984c-d582cb8c9a87.png)

imm registry status:
![image](https://cloud.githubusercontent.com/assets/8129541/11598258/ccd4220e-9a8e-11e5-80c2-131da4fe9502.png)

also changed substance/treatment refusal reason and completion code as per the TDSCorrections.docx
![image](https://cloud.githubusercontent.com/assets/8129541/11598371/821154ac-9a8f-11e5-8f32-c153e3d97709.png)

**Comment by Jungyubw** [comment]
fixed by Srini and Updated on TCAMT
