### ISSUE TITLE
Test Data Specification--Element "Administered Code" 

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#219]
This is from Craig.

In the Test Data Specification, the Element "Administered Code" would probably be better if it were labeled "Administered Vaccine". The "data" value isn't a code.

**Comment by smartinez290** [comment]
@sriniadhiwork please, change the element "Administered Code" to "Administered Vaccine" in the Vaccine Administration  Information Table for all the test cases in the Administration Group.

**Comment by sriniadhiwork** [comment]
Woo: please use please use common_tdspec.xsl [2.9.8](https://sourceforge.net/p/nistmu2hl7xslt/svn/HEAD/tree/trunk/xsl/common/common_tdspec.xsl)

![image](https://cloud.githubusercontent.com/assets/8129541/11598313/288dfd0e-9a8f-11e5-8d36-a3c6c1b6b320.png)

**Comment by Jungyubw** [comment]
fixed by Srini and Updated on TCAMT
