### ISSUE TITLE
AD message ACKs inconsistent TDS

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#220]
The first 6 have a message the last 4 do not . The last four need to be like the first six.

First 6:

![image](https://cloud.githubusercontent.com/assets/14874904/11577755/56c0074a-99ee-11e5-9719-7da8dcb883c8.png)

Last 4:

![image](https://cloud.githubusercontent.com/assets/14874904/11577772/84fc49fc-99ee-11e5-926d-79d14f2d4543.png)

**Comment by smartinez290** [comment]
@sriniadhiwork The last four ACK Test cases  are missing the information in the data specification.

**Comment by sriniadhiwork** [comment]
Woo: need your help, this wasn't showing in tcamt either - wondering if this is this an xsl issue or a tcamt fix?

**Comment by Jungyubw** [comment]
XSLT will be modified by Srini

**Comment by sriniadhiwork** [comment]
Hi Woo,

could you please pickup the latest. thanks!

[common_tdspec.xsl] (https://sourceforge.net/p/nistmu2hl7xslt/svn/HEAD/tree/trunk/xsl/common/common_tdspec.xsl)

thanks,
srini

**Comment by Jungyubw** [comment]
fixed by Srini and Updated on TCAMT
