### ISSUE TITLE
CDC Immunization Project (CNI) in Test Package 

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#226]
CDC Immunization Project (CNI) should be removed from the test package.

**Comment by haffo** [comment]
@Jungyubw  Please remove the CDC test cases from resource bundle. Make sure you have a backup somewhere.

**Comment by Jungyubw** [comment]
Done. We can generate these CDC Test Plan on TCAMT if needed.

**Comment by smartinez290** [comment]
@Jungyubw no ready for QA, I guess I have to wait for the next tool deployment.
