### ISSUE TITLE
Test Packate PDF Cover Page Template

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#227]
Rob, 

Here is the template for the cover page for your review.
![coverpage](https://cloud.githubusercontent.com/assets/14842422/11601219/914dafe6-9a9f-11e5-8711-641ab94bf19d.png)

**Comment by robnist** [comment]
2015 Edition ONC Certification Test Data

Version is 1.0

Note, TCAMT version and ONC published version are different. Woo may have to add another attribute.

**Comment by smartinez290** [comment]
@Jungyubw see attachm
[TestpackageCoverPage.pptx](https://github.com/haffo/hit-iz-tool/files/116028/TestpackageCoverPage.pptx)
ent and let me know if you need additional information.

**Comment by smartinez290** [comment]
@Jungyubw, The Test Package Cover page is not shown in the latest tool release.

**Comment by Jungyubw** [comment]
Done
