### ISSUE TITLE
Help button for Error Description

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#243]
Replace the current validation description (1st screenshot) with the 2nd (except remove what is in red, that is only for my slide for ATL training). Note, I included the raw table as well so you can copy and paste.

![image](https://cloud.githubusercontent.com/assets/14874904/12176751/f2d055be-b536-11e5-9851-248681e49b6a.png)

![image](https://cloud.githubusercontent.com/assets/14874904/12176755/f8419828-b536-11e5-8b6c-8328c692c0fa.png)

Category	Description
Errors		Indicates non-conformance to a requirement.
	Errors do constitute a failed validation
Warnings		Provides information about potential missing support for a requirement or recommendation.
	Warnings do not constitute a failed validation
Alerts		Provides information about how the validation verifies or does not verify requirements. For example, the specification may provide a value set binding to an element but the value set is empty. Therefore, the user is alerted to the fact that no meaningful validation can be performed.
	Alerts do not constitute a failed validation
Affirmatives		Provides an indication of a positive outcome to a validation assertion
	Affirmatives are not listed by default (user preference)

**Comment by smartinez290** [comment]
@haffo use the attached file.

**Comment by smartinez290** [comment]
Sorry 
[1-Validation Result Information v1 012216.docx](https://github.com/haffo/hit-iz-tool/files/114313/1-Validation.Result.Information.v1.012216.docx)
Here is the attachment.

**Comment by smartinez290** [comment]
Per @robnist, @haffo please remove the bullets in the first table, that was just for the slides.

**Comment by smartinez290** [comment]
@haffo please update the document again. Rob made some changes. see attachment.
[ValidationResultHelpButton.docx](https://github.com/haffo/hit-iz-tool/files/115967/ValidationResultHelpButton.docx)

**Comment by smartinez290** [comment]
@haffo Nicholas sent you the html version.

**Comment by smartinez290** [comment]
@haffo never mind, do not use Nicholas doc use the attached doc, this is the one Rob set out.  I hope you are not confused.
