### ISSUE TITLE
change notes to tester in TC 1

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#244]
remove TCA

add fields for multiple occurrences

maybe add in other cases where this applies

**Comment by smartinez290** [comment]
@robnist is this one related to the other ticket? it also calls for other updates. This one is assigned to you also.

**Comment by robnist** [comment]
Fixed in TCAMT.

**Comment by smartinez290** [comment]
@robnist should I close this ticket? not sure how to QA part of it.
