### ISSUE TITLE
Note to Testers

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#248]
Per Rob S: "We changed this to Content. t. Need to find locations and change." See attachmen
![tca-tc_to content](https://cloud.githubusercontent.com/assets/14842422/12554391/50a6102c-c34a-11e5-9d9e-285f58a4b4fa.png)

**Comment by smartinez290** [comment]
@robnist I had this ticket assigned to you. This update is not reflected in the latest release.

**Comment by robnist** [comment]
Fixed in TCAMT
