### ISSUE TITLE
 Message content

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#25]
Message content font size can be increased a little (match that of the TDS)

**Comment by smartinez290** [comment]
@sriniadhiwork is this ticket fixed and waiting for tool redeployment?

**Comment by sriniadhiwork** [comment]
Fixed the  message content -  preview [here](http://embed.plnkr.co/XmulPVr7qriTWkvSOYXx/preview)
- tcamt use common_messagecontent.xsl [v1.8.1] (https://sourceforge.net/p/nistmu2hl7xslt/svn/HEAD/tree/trunk/xsl/common/common_messagecontent.xsl)

**Comment by Jungyubw** [comment]
fixed

**Comment by sriniadhiwork** [comment]
hi Woo.. just for clarification.. the latest message content xml has to be used and the resource bundle be regenerated and the iztool has to be deployed using this resource bundle for the changes to be visible in the iztool, right?
