### ISSUE TITLE
NIST Normative Test Process Document date posted

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#253]
The date posted in the tool does not match the date in the document. @robnist please let us know if they should match.

**Comment by robnist** [comment]
Should be the same for this type of thing.

________________________________
On: 04 February 2016 09:04, "smartinez290" <notifications@github.com> wrote:

The date posted in the tool does not match the date in the document. @robnist<https://github.com/robnist> please let us know if they should match.

-
