### ISSUE TITLE
SOAP Envelope & Connectivity tests not detecting non-HL7 message

### ISSUE THREAD

**Issue by mindovina** [haffo/hit-iz-tool#280]
On hit-dev, it *works* for:

SOAP Envelope 
-> Sender(Initiator)  SOAPENV_2_SubmitSingleMessage_Request

but it does NOT work for 

SOAP Envelope 
-> Receiver(Responder)  SOAPENV_2_SubmitSingleMessage_Response

It *works* for:

-> Sender(Initiator)  SOAPCON_3_SubmitSingleMessage_Message

but it does NOT work for:

-> Receiver(Responder)  SOAPCON_2_SubmitSingleMessage_Response

**Comment by haffo** [comment]
fixed. will deploy after I complete some new requirements I got from Rob last friday

**Comment by mindovina** [comment]
for both SOAP Envelope and SOAP Connectivity?


________________________________

**Comment by mindovina** [comment]
I'm testing the hit-dev version but don't see any change ?


________________________________
