### ISSUE TITLE
Test categories

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#3]
Provide as documentation in IZ Tool. See attachment.
[TestDataCategoriesD3.docx](https://github.com/haffo/hit-iz-tool/files/3721/TestDataCategoriesD3.docx)

**Comment by robnist** [comment]
This is old. What I am I supposed to do?

**Comment by smartinez290** [comment]
This is the Test categories documentation, that you want to include in the tool.

**Comment by robnist** [comment]
OK, it is in version 6 of the document. I’ll review what is on tool for validation and add this as well.
