### ISSUE TITLE
 reference to profile/version and validation context file.

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#31]
The validation report needs to include reference to profile/version and validation context file.

**Comment by smartinez290** [comment]
Per meeting discussion: The profile section of the validation report should be updated to include;
Name = name of the profile (see Profile information to get the names. 
Message Type = ex. VXU_V04
Standard =  HL7 Version 2.5.1

**Comment by robnist** [comment]
Sandra,

Please provide explicitly what is to be included for each profile.

Message Type is VXU^V04^VXU_V04
Profile ID = Z22

One thing to change is the Standard; this needs to refer to the IG and release.

Please create an explicit list of changes for me to review.

Based on our conversations today we need to provide better documentation of what needs to be changed.

Thanks
Rob

**Comment by smartinez290** [comment]
See attached file for updates to the profile section of the validation report. Woo will provide the missing attributes.
[Message Validation ReportCFCB.docx | uploaded via ZenHub](https://files.zenhub.io/561e59f43f6316ae5bed9a47)

**Comment by smartinez290** [comment]
See updated file, with all the attributes. 
[Message Validation ReportCFCB.docx | uploaded via ZenHub](https://files.zenhub.io/561e61a23f6316ae5bed9ad3)

**Comment by HossamT** [comment]
@haffo It has been updated in version 0.0.5-SNAPSHOT of the unified report

**Comment by smartinez290** [comment]
The report is still missing the Profile type, Profile Date and Profile Standard. See the previous attached file.

**Comment by HossamT** [comment]
The link is there, but there is no information to show in the profile file, the metadata fields should be populated @Jungyubw

**Comment by smartinez290** [comment]
Also, take a look at the Context-Free report. There is no Test cases for context free, this section should not be included in the report.

**Comment by HossamT** [comment]
It's handled by the Tool, if you don't specify test case information there will be no Test Case section in the report. @haffo can you look at that, it seems that you are specifying test case information for Context-Free validation.
