### ISSUE TITLE
Information category

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#33]
Information is still a category—need to decide what to do with that.

**Comment by smartinez290** [comment]
@robnist can I close this ticket?

**Comment by robnist** [comment]
Yes, in the code it should just be commented out and there should be no evidence that it every existed on the tool.

**Comment by robnist** [comment]
I didn't mean to close. Check on those things and then close if OK.

**Comment by robnist** [comment]
Seems to me informational does not appear anywhere; but I didn't check documentation. Please check and if OK, then close.
