### ISSUE TITLE
failure interpretation

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#34]
Need better indicator to open failure interpretation up. Please discuss with Rob.

**Comment by smartinez290** [comment]
Per meeting discussion, just add a "+" button to the "Failures interpretation" section of the Message Validation Report.

**Comment by robnist** [comment]
No, a “View” button.

**Comment by HossamT** [comment]
@haffo It has been updated in version 0.0.5-SNAPSHOT of the unified report
