### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#37]
Fix sliding info page in the tool  front page.  
Indicate ONC Certification on beginning page (Click here for ONC cert).
Make slider smaller so most screens will see all the information with having to scroll.

**Comment by smartinez290** [comment]
@robnist The ticket is here, but Harold needs a full description of what he needs to do. He forgot what you told him. He does have the file that you sent him.

**Comment by robnist** [comment]
Add a now section "Acknowledgements" after "About" and before "Disclaimer"

**Comment by haffo** [comment]
>> Add a now section "Acknowledgements" after "About" and before "Disclaimer" 
This response is for issue #89, right ?

**Comment by robnist** [comment]
Yes.

**Comment by smartinez290** [comment]
@robnist Please QA this one I am not sure what you are expecting. The "About" right now is before the "Acknowledgment".

**Comment by smartinez290** [comment]
@robnist never mind. I am closing this one.
