### ISSUE TITLE
Context-based: Test categories

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#4]
Ensure validation engine/constraints provide support for each test categories and  provide a separate category for context validation. See attached files for explanation of test categories. 
[TestDataCategoriesD3.docx](https://github.com/haffo/hit-iz-tool/files/3727/TestDataCategoriesD3.docx)

**Comment by smartinez290** [comment]
Done. Move to QA

**Comment by smartinez290** [comment]
@HossamT I  don't see the separate category in the "Message Validation Result".  Should I  be talking to Harold about this?

**Comment by HossamT** [comment]
@smartinez290 No, It hasn't been done yet, we had a meeting yesterday about that, it needs more time.
