### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#42]
Provide list of error messages

**Comment by smartinez290** [comment]
Sandra to provide Error detection documentation to Harold.

**Comment by smartinez290** [comment]
@haffo used the attached file for the error detection information. This is the information Rob is requesting to have in the Message Validation Result panel. Add and "i" icon just like you did with the profile information. Could you please verify the document to make sure I did not have anything wrong? Hossam reviewed it but he said that you might have change some of the detection errors description or name for presentation purposes in the tool.
[Message Validation Results.docx](https://github.com/haffo/hit-iz-tool/files/15251/Message.Validation.Results.docx)

**Comment by HossamT** [comment]
@haffo I was talking about the configuration file you are using in the tool regarding the classification of the categories

**Comment by haffonist** [comment]
@HossamT 
Here is the file I am using 

[application.conf | uploaded via ZenHub](https://files.zenhub.io/5628094d88bd18e23150ff6d)
