### ISSUE TITLE
 HL70301_IZ in Z22, Z34, Z44, Z31, Z32, Z42 

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#56]
Please update table HL70301, the description should be ISO instead or OID.

**Comment by Jungyubw** [comment]
fixed and ready to QA after next deployment

**Comment by smartinez290** [comment]
Woo -- Why is table 0301 not constrained?  the only value there should be ISO? It was fine before the redeployment. Did you do something that override the values? The only thing wrong was the description.

**Comment by smartinez290** [comment]
Never mind! I was looking at tge HL7 table and not at the CDC-HL7-IZ.
