### ISSUE TITLE
CS Z23 not supported in IZ22

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#57]
The tool is not validating against  IZ-23 CS: If RXA-20 is valued "CP" or "PA"  and the first occurrence of RXA-9.1 (Administration Note.code) is “00” then the message SHALL include an OBX segment associated with the RXA with OBX-3.1 shall equal “64994-7”

**Comment by Jungyubw** [comment]
I need to help from Hoosam for this. I will update it after he comes back

**Comment by Jungyubw** [comment]
done. Ready to QA

**Comment by smartinez290** [comment]
waiting for Resource bundle to be release.
