### ISSUE TITLE
 RXA-9 validation - filtering the report based on parameters 

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#58]
Can we NOT validate the 2nd occurrence of RXA-9? The IG makes a provision to allow only RXA-9.2 any occurrence after the first (i.e., send text only). So what I want to do is not to have anything reported for errors for RXA-9 after the first occurrence. I’m thinking the best way to do this is to filter the Error report. This way the validation does not have to be messed with. See attachment. it was agreed to filter the report based on parameters. Hossam, I know you are aware of the issue and probably working on it, I added to the ticket to follow up with testing when implemented.

**Comment by smartinez290** [comment]
[5ure6onq.bmp | uploaded via ZenHub](https://files.zenhub.io/560ad7017a763234615d683b)

**Comment by HossamT** [comment]
@haffo Using the Unified Report artifact (report-filter module)
groupId : gov.nist.healthcare.hl7.v2.unifiedreport
artifactId : report-filter
version : 0.0.4-SNAPSHOT

Usage : 
// Create a restriction 
Restriction restriction = new Restriction();
restriction.add(new Condition("path",Exp.Format,"RXA\\[[1-9]+[0-9]*\\]-9\\[2\\](\\.[1-9]+[0-9]*)*"));
restriction.setAction(Action.Remove);

//Create a filter
Filter f = new Filter();

//Add restriction to filter
f.restrain(restriction);

//Filter report
EnhancedReport filtered = f.filter(report);

**Comment by haffo** [comment]
@HossamT  "RXA\[[1-9]+[0-9]\]-9\[2\](\.[1-9]+[0-9])*" is not a valid regex expression in java.

**Comment by HossamT** [comment]
Sorry, GitHub removes some characters from the comments (like double \\ and some *). I'll send you the regex by email.
