### ISSUE TITLE
ERR-4 Max Length on Z23, Z31 and Z42

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#63]
ERR-4 max length must be 1.

**Comment by Jungyubw** [comment]
fixed, please review it after next reployment

**Comment by smartinez290** [comment]
Z23 and Z42 are still showing length [1,2]

**Comment by Jungyubw** [comment]
Modified and it will be shown by next redeployment

**Comment by smartinez290** [comment]
Length is still wrong. There was a tool redeployment today.

**Comment by Jungyubw** [comment]
Already fixed for my updapte. Do you make sure updated profile was included in this redeployment?
