### ISSUE TITLE
Message Validation Report - Context- based update

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#70]
Add a Test case section. See attachment. 
[Message Validation Report_CB_TC.docx | uploaded via ZenHub](https://files.zenhub.io/561e56e43f6316ae5bed9a0a)

**Comment by HossamT** [comment]
@haffo It has been updated in version 0.0.5-SNAPSHOT of the unified report

In order to a Test case section to the report : 
report.setTestCase("Plan", "Group", "Case", "Step");
