### ISSUE TITLE
Message Validation Report download option

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#72]
Add download options on the top right corner of the "Message Validation Report"   It should allow to download as PDF, Word, HTML and XML. Use the MU-2 icons. See attachment. 
![downloadicons](https://cloud.githubusercontent.com/assets/14842422/10487489/34c2e7b0-7262-11e5-8a0b-4f87c2a86bdc.png)

**Comment by HossamT** [comment]
This concerns the GUI it's @haffo's task

**Comment by robnist** [comment]
I see it in context-free already.

[cid:image001.png@01D10678.55DFAF60]
