### ISSUE TITLE
"Message Validation Result" new error category - Context-based (only)

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#74]
Add a "Content" error sub-category under the "Error" category to display only the errors generated by the  assertions coming from TCAMT. All other constraint failures (IZ-XX) should be displayed under the "Constraint Failure" sub-category.

**Comment by smartinez290** [comment]
Hossam why is this issue in a pending status? Do you need something from Woo or Harold?

**Comment by HossamT** [comment]
I need some information from Woo, I set a meeting with him for Monday

**Comment by smartinez290** [comment]
Ok!! Thanks.
