### ISSUE TITLE
XCN_IZ Update Z22, Z32 and Z42

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#75]
The XCN_IZ needs to be updated. XCN_IZ.9 should be HD_IZ. The following segments are using XCN_IZ: ORC-10, ORC-12 and RXA-10. Please update the identified profiles accordingly.

**Comment by Jungyubw** [comment]
fixed and will be shown at next deployment

**Comment by smartinez290** [comment]
The fixed was not reflected in today's redeployment.

**Comment by Jungyubw** [comment]
Already fixed for my updapte. Do you make sure updated profile was included in this redeployment?
