### ISSUE TITLE
Home Page Icons need to be combined

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#77]
@abrown21 the EHR-S and IIS icons need to be combined into one icon. It should read  EHR-S & ISS. Rob mentioned that Ryan had designed this icons and you should have the originals. When you are done please send them to Haroloda and move this ticket to QA for review.

**Comment by abrown21** [comment]
![ehrs iss](https://cloud.githubusercontent.com/assets/14879645/10668710/919c8cc6-78ab-11e5-91bc-0696a9b2101d.PNG)

**Comment by smartinez290** [comment]
@haffo I don't see the new Icon in the tool.

**Comment by smartinez290** [comment]
it  is in the hit-testing, but not in the dev site.
