### ISSUE TITLE
Installation Guide 

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#78]
@abrown21 the attached installation guide is from the Immunization MU-2 tool, but it can be used in the IZtool. Please update this document using IZtool screen shots.
[Installation Guide - NIST HL7v2 Validation Tools v1-1.docx | uploaded via ZenHub](https://files.zenhub.io/56252b9fa05629b30ffb9585)

**Comment by abrown21** [comment]
Section IV of the Installation guide says to download the war file. The war file is not currently in the documentation menu. There are also no documentations in the Tool Download section. Therefore I can not obtain the appropriate screen shots.

Has the war.file name been changed?

**Comment by smartinez290** [comment]
@abrown21 the war file is not available yet.
