### ISSUE TITLE
Multilple value set binding

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#79]
The tool is not validating RXA-5 on VXY-Z22 profile which has a binding to CVX and NDC. Rob mentioned that there is a solution for this type of validation.

**Comment by smartinez290** [comment]
What is the status on this issue?

**Comment by HossamT** [comment]
Multiple value sets binding is working, I didn't close the ticket because we are still testing it and have to agree on the detections reported for each case

**Comment by smartinez290** [comment]
Is @Rob doing the testing and reviewing the detections? I move it to "Waiting for QA"
