### ISSUE TITLE
     IZ-AD-2_Admin_Adult IZ-AD-2.1_Send_V04_Z22 -- RXA[1].21 -- Extra space

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#81]
TCA-180 - Expected test case fixed content is missing. The value at ORDER[2].RXA[1].21[1](Action Code - RXA) does not match the expected value: 'A '.  ---- TCAMT is adding a space at the end of line.

**Comment by Jungyubw** [comment]
fixed

**Comment by Jungyubw** [comment]
But we need update resource bundle and deploy the tool.

**Comment by smartinez290** [comment]
Woo -- Was the resource bundle updated?

**Comment by Jungyubw** [comment]
Not yet. need to TCAMT update first.

**Comment by smartinez290** [comment]
I am still getting this error. Could you take a look?

**Comment by Jungyubw** [comment]
fixed
