### ISSUE TITLE
     IZ-AD-2_Admin_Adult IZ-AD-2.1_Send_V04_Z22  - RXA-10.9

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#85]
TCA-115-4 - Expected content is missing. The empty value at ORDER[2].RXA[1].10[1].9[1](Assigning Authority) is expected to be present.

The tool is evaluating "Presence-Content Indifferent", as defined by Craig in the default data categorization. This is a base node, no data categorization should be assigned. 

Woo will be discussing this issue with @robnist

**Comment by smartinez290** [comment]
Woo, The JPEG that you sent me yesterday was not for Z22, but for Z42, the data categorization is correct in Z22. Therefore the issue on why we are getting a presence - content indifference  error on RXA-10.9 is  still need to be solved.

I did found some base node with a categorization assigned. See attachment for my analysis.
[Copy of TCAMT test data default categories 20151012_Woo.xlsx](https://github.com/haffo/hit-iz-tool/files/18495/Copy.of.TCAMT.test.data.default.categories.20151012_Woo.xlsx)

**Comment by Jungyubw** [comment]
fixed
