### ISSUE TITLE
Funny characters in TEXT

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#87]
![image](https://cloud.githubusercontent.com/assets/14874904/10666602/9a8dd0a2-78a0-11e5-8fd2-7c9437d5c010.png)

**Comment by Jungyubw** [comment]
Sandra, please remove Microsoft characters in the Test Story

**Comment by robnist** [comment]
What is the source of the problem? If we go back in an edit will this reoccur? We need to solve the root of the problem.

**Comment by Jungyubw** [comment]
Anusha has provided new XSL for Test Story.
In the tcamt, the funny character is gone. but we need to check in the IZ-tool after deployment,

**Comment by smartinez290** [comment]
There are still funny characters in the text.

**Comment by Jungyubw** [comment]
fixed.

**Comment by Jungyubw** [comment]
Sandra, I need to disucss about this issue.
