### ISSUE TITLE
"About" page update

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#89]
Add the following text in the About page:

This Test Suite, the test data, and associated artifacts were developed by the National Institute of Standards and Technology (NIST) in collaboration with the Center for Disease Control and Prevention (CDC) and American Immunization Registries Association (AIRA).

**Comment by haffo** [comment]
@smartinez290  Which section is this going to ? Currenly we habe two section: confidentiality and disclaimer.

**Comment by haffo** [comment]
@robnist Which section is this going to ? Currenly we have two section: confidentiality and disclaimer.

**Comment by smartinez290** [comment]
@robnist Harold told me that you asked for other changes. Can you QA  this one when done?
