### ISSUE TITLE
Plz Add Client-side Certificate support to SOAP Connectivity Test

### ISSUE THREAD

**Issue by mindovina** [haffo/hit-iz-tool#93]
Some IIS require their clients to authenticate via a certificate. This is a certificate which the client side (IZ tool in our case) needs to generate and send to the IIS as part of the sign-up/account creation process. Currently the IZ Tool's SOAP Connectivity Test component does not support this.

**Comment by mindovina** [comment]
Some IIS require their clients to authenticate via a certificate.   This is a certificate which the client side (IZ tool in our case) needs to generate and send to the IIS as part of the sign-up/account creation process.  Currently the IZ Tool's SOAP Connectivity Test component does not support this.

**Comment by smartinez290** [comment]
@mindovina @haffo was this ticket resolved, can I close it? @mindovina make sure to QA this one.

**Comment by mindovina** [comment]
I don't think so, harold?


________________________________

**Comment by haffo** [comment]
no, in progress. It will be part of the generic transport framework that I am developing.  Harold
