### ISSUE TITLE
Test story font size still does not match

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#97]
Test story font size still does not match

![image](https://cloud.githubusercontent.com/assets/14874904/10741637/39aaee02-7bff-11e5-924f-e7a91d84ab7a.png)

**Comment by Jungyubw** [comment]
it was already fixed and it will be shown corettly at next deployment

**Comment by robnist** [comment]
According to this deployment was at 3:00 PM today....it was fixed since then???

![image](https://cloud.githubusercontent.com/assets/14874904/10742231/712f0824-7c02-11e5-880e-f2a106d03534.png)

**Comment by Jungyubw** [comment]
I didn't provide updated resource bundle to Harold yet.
I will come soon.
In this resource bundle, test story is generated by Anusha's XSL.

**Comment by Jungyubw** [comment]
Just Plain text is okay to show.
But If user inputted own style text. it will be shown different.

In this case, user needs to update test story.
